import type { TableDesignDriverProfile } from ".";

export const mysqlTableDesignProfile: TableDesignDriverProfile = {
    driver: "mysql",
    displayName: "MySQL",
    typeCatalog: [
        {
            family: "string",
            baseType: "varchar",
            label: "VARCHAR",
            supportsLength: true,
            defaultLength: "255",
        },
        {
            family: "string",
            baseType: "char",
            label: "CHAR",
            supportsLength: true,
            defaultLength: "36",
        },
        { family: "string", baseType: "text", label: "TEXT" },
        { family: "number", baseType: "int", label: "INT", supportsUnsigned: true },
        { family: "number", baseType: "bigint", label: "BIGINT", supportsUnsigned: true },
        {
            family: "number",
            baseType: "decimal",
            label: "DECIMAL",
            supportsPrecisionScale: true,
            supportsUnsigned: true,
            defaultPrecision: "10",
            defaultScale: "2",
        },
        {
            family: "datetime",
            baseType: "datetime",
            label: "DATETIME",
            supportsTimePrecision: true,
        },
        {
            family: "datetime",
            baseType: "timestamp",
            label: "TIMESTAMP",
            supportsTimePrecision: true,
        },
        { family: "datetime", baseType: "date", label: "DATE" },
        { family: "boolean", baseType: "boolean", label: "BOOLEAN" },
        { family: "json", baseType: "json", label: "JSON" },
        { family: "binary", baseType: "blob", label: "BLOB" },
        {
            family: "custom",
            baseType: "enum",
            label: "ENUM",
            supportsEnumValues: true,
        },
    ],
    indexMethods: ["btree", "hash"],
    tableOptions: [
        { id: "engine", label: "Engine" },
        { id: "charset", label: "Charset" },
        { id: "collation", label: "Collation" },
        { id: "comment", label: "Comment" },
    ],
    columnOptions: {
        charset: true,
        collation: true,
        generatedStorage: true,
        identityOptions: false,
        unsigned: true,
        charSemantics: false,
    },
    constraintOptions: {
        enforced: true,
        comments: false,
    },
    defaults: {
        columnType: {
            mode: "structured",
            family: "string",
            baseType: "varchar",
            length: "255",
            precision: "",
            scale: "",
            timePrecision: "",
            unsigned: false,
            charSemantics: "",
            enumValues: [],
            rawTypeName: "",
        },
        indexMethod: "btree",
        identityGeneration: "by_default",
    },
};
