import type { TableDesignDriverProfile } from ".";

export const oracleTableDesignProfile: TableDesignDriverProfile = {
    driver: "oracle",
    displayName: "Oracle",
    typeCatalog: [
        {
            family: "number",
            baseType: "NUMBER",
            label: "NUMBER",
            supportsPrecisionScale: true,
            defaultPrecision: "10",
            defaultScale: "0",
        },
        {
            family: "string",
            baseType: "VARCHAR2",
            label: "VARCHAR2",
            supportsLength: true,
            supportsCharSemantics: true,
            defaultLength: "255",
        },
        {
            family: "string",
            baseType: "NVARCHAR2",
            label: "NVARCHAR2",
            supportsLength: true,
            defaultLength: "255",
        },
        {
            family: "string",
            baseType: "CHAR",
            label: "CHAR",
            supportsLength: true,
            supportsCharSemantics: true,
            defaultLength: "1",
        },
        { family: "datetime", baseType: "DATE", label: "DATE" },
        {
            family: "datetime",
            baseType: "TIMESTAMP",
            label: "TIMESTAMP",
            supportsTimePrecision: true,
            defaultTimePrecision: "6",
        },
        { family: "string", baseType: "CLOB", label: "CLOB" },
        { family: "binary", baseType: "BLOB", label: "BLOB" },
    ],
    indexMethods: [],
    tableOptions: [{ id: "comment", label: "Comment" }],
    columnOptions: {
        charset: false,
        collation: false,
        generatedStorage: false,
        identityOptions: true,
        unsigned: false,
        charSemantics: true,
    },
    constraintOptions: {
        enforced: true,
        comments: false,
    },
    defaults: {
        columnType: {
            mode: "structured",
            family: "number",
            baseType: "NUMBER",
            length: "",
            precision: "10",
            scale: "0",
            timePrecision: "",
            unsigned: false,
            charSemantics: "",
            enumValues: [],
            rawTypeName: "",
        },
        indexMethod: "",
        identityGeneration: "by_default",
    },
};
