import type { TableDesignDriverProfile } from ".";

export const postgresTableDesignProfile: TableDesignDriverProfile = {
    driver: "postgres",
    displayName: "PostgreSQL",
    typeCatalog: [
        {
            family: "string",
            baseType: "varchar",
            label: "VARCHAR",
            supportsLength: true,
            defaultLength: "255",
        },
        { family: "string", baseType: "text", label: "TEXT" },
        { family: "number", baseType: "integer", label: "INTEGER" },
        { family: "number", baseType: "bigint", label: "BIGINT" },
        {
            family: "number",
            baseType: "numeric",
            label: "NUMERIC",
            supportsPrecisionScale: true,
            defaultPrecision: "10",
            defaultScale: "2",
        },
        {
            family: "datetime",
            baseType: "timestamp",
            label: "TIMESTAMP",
            supportsTimePrecision: true,
        },
        {
            family: "datetime",
            baseType: "timestamptz",
            label: "TIMESTAMPTZ",
            supportsTimePrecision: true,
        },
        { family: "datetime", baseType: "date", label: "DATE" },
        { family: "boolean", baseType: "boolean", label: "BOOLEAN" },
        { family: "json", baseType: "jsonb", label: "JSONB" },
        { family: "uuid", baseType: "uuid", label: "UUID" },
        { family: "binary", baseType: "bytea", label: "BYTEA" },
    ],
    indexMethods: ["btree", "hash", "gin", "gist", "brin"],
    tableOptions: [{ id: "comment", label: "Comment" }],
    columnOptions: {
        charset: false,
        collation: true,
        generatedStorage: true,
        identityOptions: true,
        unsigned: false,
        charSemantics: false,
    },
    constraintOptions: {
        enforced: false,
        comments: false,
    },
    defaults: {
        columnType: {
            mode: "structured",
            family: "string",
            baseType: "varchar",
            length: "255",
            precision: "",
            scale: "",
            timePrecision: "",
            unsigned: false,
            charSemantics: "",
            enumValues: [],
            rawTypeName: "",
        },
        indexMethod: "btree",
        identityGeneration: "by_default",
    },
};
