import { describe, expect, test } from "bun:test";

import { updateCargoLockPackageVersion } from "./sync-version-utils.js";

const cargoLockFixture = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "NexusPilot"
version = "0.10.1"
dependencies = [
 "tauri-plugin-http",
]

[[package]]
name = "tauri-plugin-http"
version = "2.5.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "known-good"
`;

describe("updateCargoLockPackageVersion", () => {
  test("updates only the workspace package version", () => {
    expect(
      updateCargoLockPackageVersion(cargoLockFixture, "NexusPilot", "0.10.2"),
    ).toBe(`# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "NexusPilot"
version = "0.10.2"
dependencies = [
 "tauri-plugin-http",
]

[[package]]
name = "tauri-plugin-http"
version = "2.5.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "known-good"
`);
  });

  test("allows the workspace package to already have the target version", () => {
    expect(
      updateCargoLockPackageVersion(cargoLockFixture, "NexusPilot", "0.10.1"),
    ).toBe(cargoLockFixture);
  });

  test("rejects a lockfile without the workspace package", () => {
    expect(() =>
      updateCargoLockPackageVersion(cargoLockFixture, "MissingPackage", "0.10.2"),
    ).toThrow('Cargo.lock does not contain package "MissingPackage"');
  });
});
